Added linting with isort and black
mozilla/mozilla-schema-generator pull request #164
Opened 2020-10-18 07:33 UTC by DawoodShahat

This PR fixes #162 

- Added isort to format imports
- Added black to format code

2020-10-18 07:38 UTC, DawoodShahat commented
[CircleCI](https://app.circleci.com/pipelines/github/mozilla/mozilla-schema-generator/632/workflows/5abce96d-06c5-4d17-b354-0f7efa3b95c8/jobs/1057) catches linting errors now.

2020-10-22 16:58 UTC, wlach commented
@DawoodShahat it looks like this is failing CI, can you look into it?

2020-10-23 01:35 UTC, DawoodShahat commented
@DawoodShahat The CI is failing because of linting error. It will pass when the whole codebase is formatted with `isort` and `black`. I think I should do that in the next commit. What do you think?.

2020-10-23 14:05 UTC, wlach requested changes
Looks good @DawoodShahat, while you're here could you add a lint-fix command similar to what was implemented here (you would also need to add autoflake to the list of dependencies)? https://github.com/mozilla/glean-dictionary/blob/51374d7090a5fd74da7d96f23ad70b92e386b8e6/Makefile#L11

2020-10-23 14:59 UTC, DawoodShahat commented on Makefile
> +	black mozilla_schema_generator tests ./*.py
@wlach instead of lint-fix I've added `make format`  to format the code. As for autoflake, I will add that in the next commit.

2020-10-27 20:09 UTC, wlach commented on Makefile
> +	@echo "  lint - check style with flake8, isort and black"
We should add a target for `format`

```suggestion
	@echo "  lint - check style with flake8, isort and black"
	@echo "  format - autoformat with autoflake, isort and black"
```

2020-10-27 20:09 UTC, wlach approved these changes
Looks good minus one nit (which I went ahead and fixed). Merging.

2020-10-28 08:22 UTC, DawoodShahat commented
@wlach Thanks for the review.

2020-10-30 19:49 UTC, merged